{% set name = "nr.types" %}
{% set version = "2.5.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "bc575b3d38b1ed194bdc4c3d70f83d8fc637a0a29c8c746ca3bff44c8a8a271d"

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python
    - six
    - typing

test:
  imports:
    - nr
    - nr.types
    - nr.types._impl

about:
  home: "https://github.com/NiklasRosenstein/python-nr.types"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE.txt"
  summary: "Toolbox with useful Python classes and type magic."

extra:
  recipe-maintainers:
    - NiklasRosenstein
