{% set name = "nr.types" %}
{% set version = "4.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "45c8f2a808da4f72bfa6a5735323725371054cb1d954792a67f4163f431b296f"

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python
    - deprecated
    - six
    - typing

test:
  imports:
    - nr.types
    - nr.types.abc
    - nr.types.collections
    - nr.types.generic
    - nr.types.interface
    - nr.types.meta
    # We don't expect the persist module to be importable as it requires
    # nr.fs, but it's intentionally not listed as a dependency (so users
    # can actively decide to depend on nr.fs).
    #- nr.types.persist
    - nr.types.singletons
    - nr.types.struct
    - nr.types.stream
    - nr.types.sumtype
    - nr.types.utils.classdef
    - nr.types.utils.funcdef
    - nr.types.utils.function
    - nr.types.utils.logging
    - nr.types.utils.module
    - nr.types.utils.typing

about:
  home: "https://github.com/NiklasRosenstein/python-nr.types"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE.txt"
  summary: "Toolbox with useful Python classes and type magic."

extra:
  recipe-maintainers:
    - NiklasRosenstein
