{% set name = "nr.types" %}
{% set version = "2.5.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "e54e390ac7497a43f44c3a7b68241645c0d116fdf79f213a20345210fcd0af5f"

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python
    - six
    - typing

test:
  imports:
    - nr
    - nr.types
    - nr.types._impl

about:
  home: "https://github.com/NiklasRosenstein/python-nr.types"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE.txt"
  summary: "Toolbox with useful Python classes and type magic."

extra:
  recipe-maintainers:
    - NiklasRosenstein
