travis:
  secure:
    BINSTAR_TOKEN: ryiqg85F4DRvtLYeuWIGcJ4vqPjfX7WY3INhyuspfAD9k7SDcQddHRksfaPAs47qmTc19+aEOReXrbKSLL8VD4gc+f77ZJ5dg7PCdg6nhChFQ5HhugZGuGqvMvYmlyu8pzDSu0gXgdxNEZODKhiUzbc2vlJ8wXqRzVZKYsPkfGQPBTEStBMGnAZGWR3c+zlDMi2qi2DqUQF0QX3FOhx6Ib4MID0tEJRQLBHIZn3G0VpvzjRRidwRl34H+jcKOWbwvq7LJo2ywbcvIzkgHhzKlVOKkJPSHvSu7U0/n1KBjLyfTp5cKK/cbRvf9W53IyJgz5mxYeclSyUXGyY0yCaT/oeIoLhKyS3570oG+jo+lZtxszvh8OqdUClAUFbENOBORugbUbCYbLZQgYcNuDd02gaR2sC+0pRQvHsqXcjyjdW/3zP7dFP1Z9Epl21hTayc9W2Z/0kdmydnSHwyTxaYChudlfHJQZec0GtHp3LA5NoR9ANUPkqTHZ2HldHuZ29E4CSRd6yPTmS6GABEkOZxjGE9HSA49UQnwWndb2fRDFoa4hmcj/9w/BogM/46Qk/pVS3wy+0mM/EvNI/+xXb2eSlpA3h/wuHl8sNwWxr363PidA7G+OXqbnYcnjRzVc+lxgRBHPq5T5+ZATT0ATQVFoRWjzuDChN0nCGml6oGfLE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
